DROP DATABASE IF EXISTS module8Schema;
CREATE DATABASE IF NOT EXISTS module8Schema;
USE module8Schema;
CREATE TABLE IF NOT EXISTS `users` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(20) NOT NULL,
  last_name VARCHAR(20) NOT NULL,
  user_name VARCHAR(20) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password TEXT NOT NULL,
  last_logged_in TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  access_level TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS `products` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  price DECIMAL NOT NULL,
  description TEXT NOT NULL,
  image TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS `cart` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  checked_out BOOLEAN NOT NULL DEFAULT FALSE,
  user_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS `cart_products` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  quantity INTEGER NOT NULL,
  cart_id INT NOT NULL,
  FOREIGN KEY (cart_id) REFERENCES cart(id),
  products_id INT NOT NULL,
  FOREIGN KEY (products_id) REFERENCES products(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS `blogs` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS `reviews` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title TEXT NOT NULL,
  review_text TEXT NOT NULL,
  product_id INT NOT NULL,
  rating INT NOT NULL DEFAULT 0,
  FOREIGN KEY (product_id) REFERENCES products(id),
  user_id INT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id),
  commentdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);