USE mySchema;
CREATE TABLE comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name TEXT NOT NULL,
  title TEXT NOT NULL,
  comment_text TEXT NOT NULL,
  commentdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);